volumes:
  db-data:

services:
  database:
    image: ghcr.io/kvdomingo/postgresql-pig:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - 5400:5432
