-- migrate:up
CREATE EXTENSION IF NOT EXISTS pg_idkit;

CREATE OR REPLACE FUNCTION IMMUTABLE_NOW()
RETURNS TIMESTAMPTZ
LANGUAGE SQL
IMMUTABLE
RETURN NOW();


CREATE TABLE wards (
  id TEXT PRIMARY KEY DEFAULT idkit_ulid_generate(),
  created_at TIMESTAMPTZ NOT NULL GENERATED ALWAYS AS (IMMUTABLE_NOW()) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE beds (
  id TEXT PRIMARY KEY DEFAULT idkit_ulid_generate(),
  created_at TIMESTAMPTZ NOT NULL GENERATED ALWAYS AS (IMMUTABLE_NOW()) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ward_id TEXT NOT NULL REFERENCES wards (id) ON DELETE CASCADE
);
CREATE INDEX beds__ward_id_ix ON beds (ward_id);

CREATE TABLE users (
  id TEXT PRIMARY KEY DEFAULT idkit_ulid_generate(),
  created_at TIMESTAMPTZ NOT NULL GENERATED ALWAYS AS (IMMUTABLE_NOW()) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE
);

CREATE TABLE patients (
  id TEXT PRIMARY KEY DEFAULT idkit_ulid_generate(),
  created_at TIMESTAMPTZ NOT NULL GENERATED ALWAYS AS (IMMUTABLE_NOW()) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  bed_id TEXT NOT NULL REFERENCES beds (id) ON DELETE CASCADE,
  is_admitted BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX patients__bed_id_ix
  ON patients (bed_id)
  WHERE is_admitted;


-- migrate:down
DROP TABLE patients;
DROP TABLE users;
DROP TABLE beds;
DROP TABLE wards;
